Origin/about
gradussus/icecream-project-20 pull request #12
Opened 2022-06-24 19:08 UTC by KL-ML

2022-06-24 19:46 UTC, gradussus requested changes

2022-06-24 19:46 UTC, gradussus commented on src/sass/components/_about.scss
> +    font-style: normal;
font-style: normal; - не потрібен

2022-06-24 19:46 UTC, gradussus commented on src/partials/about.html
> +                <source media="(min-width: 767px)"
тут max-width: 767.98px

2022-06-24 19:46 UTC, gradussus commented on src/partials/about.html
> +        <div  class="about__img-tumb">
thumb, а не tumb. Так правильніше буде

2022-06-24 19:46 UTC, gradussus commented on src/sass/components/_about.scss
> +    color: #D41443;
Усі кольори треба через scss змінні додавати, дивись паршл _variables.scss

2022-06-24 19:46 UTC, gradussus commented on src/sass/components/_about.scss
> +    background-color: #FFF5F6;
дивись паршл _variables.scss

2022-06-24 20:20 UTC, KL-ML commented on src/sass/components/_about.scss
> +    color: #D41443;
виправила

2022-06-24 20:20 UTC, KL-ML commented on src/sass/components/_about.scss
> +    background-color: #FFF5F6;
виправила

2022-06-24 20:20 UTC, KL-ML commented on src/partials/about.html
> +        <div  class="about__img-tumb">
виправила

2022-06-24 20:20 UTC, KL-ML commented on src/partials/about.html
> +                <source media="(min-width: 767px)"
виправила

2022-06-24 20:21 UTC, KL-ML commented on src/sass/components/_about.scss
> +    font-style: normal;
виправила

2022-06-25 07:07 UTC, gradussus approved these changes

2022-06-25 07:08 UTC, gradussus approved these changes

2022-06-25 07:08 UTC, merged